#!/usr/bin/env bash

export PATH=/run/wrappers/bin:/root/.nix-profile/bin:/etc/profiles/per-user/root/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin

# kea hook and switch statement for lease type
# Only continue if this is a lease renew response
hook=$1
case $hook in
  leases4_committed)
    echo "lease4_committed"
    echo $QUERY4_REMOTE_ADDR
    exit 0;;
  lease4_renew)
    echo $hook
    if [ "$QUERY4_TYPE" != "DHCPREQUEST" ]; then exit 0; fi;;
  *)
    echo $hook
    exit 0 
esac


# Read config for options set and where to locate the stateful files (e.g. imgs, ssh_keys, etc.)

config_file="/etc/massflash.conf"

. $config_file

state_dir="${state_dir:-/tmp/massflash}"

[ ! -d "$state_dir" ] && mkdir $state_dir

if [ -f $state_dir/mac-$LEASE4_HWADDR ]
then
  if grep "STATUS completed"
  then
    echo "$LEASE4_HWADDR has already been completed"
    exit 0
  elif grep "STATUS upgrading"
    echo "$LEASE4_HWADDR has already been completed"
    ./remoteflash $LEASE4_ADDRESS $LEASE4_HWADDR 2>>$state_dir/mac-$LEASE4_HWADDR
  else
    echo -n "$LEASE4_HWADDR already in progress, state: "; tail -1 $state_dir/mac-$LEASE4_HWADDR
  fi
else
    ./remoteflash $LEASE4_ADDRESS $LEASE4_HWADDR 2>$state_dir/mac-$LEASE4_HWADDR
fi
