#!/usr/bin/env bash

export PATH=/run/wrappers/bin:/root/.nix-profile/bin:/etc/profiles/per-user/root/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin

# kea hook and switch statement for lease type
hook=$1
case $hook in
  leases4_committed)
    echo "lease4_committed"
    echo $QUERY4_REMOTE_ADDR
    exit 0;;
  lease4_renew)
    echo $hook
    if [ "$QUERY4_TYPE" != "DHCPREQUEST" ]; then exit 0; fi;;
  *)
    echo $hook
    exit 0
esac

host="$LEASE4_ADDRESS"

# Read config for options set and where to locate the stateful files (e.g. imgs, ssh_keys, etc.)

config_file="/etc/massflash.conf"

. $config_file

state_dir="${state_dir:-/tmp/massflash}"
ssh_user="${ssh_user:-root}"
ssh_port="${ssh_port:-22}"

flash_sha=$(cat "${state_dir}/flash_sha")


# TODO: nc/ssh-keyscan until port 22 is up instead of sleeping
sleep 20


# TODO: Dynamic architecture/board detection
#puts "$arch"
#set archb [format "hello%s" $arch]
# Concat the arch and a string (eventually will be flash .bin)
#puts [format "hello%s" $arch]
#set archb "hello"
ap_type=$(ssh -i $state_dir/id_priv -p $ssh_port \
  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
  $ssh_user@$host "cat /etc/board.json | jq -r .model.id | cut -d',' -f2")

[ -z "ap_type" ] && echo "/etc/board.json type not parsed" && exit 1

scp -O -P $ssh_port \
  -i $state_dir/id_priv \
  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
  "$state_dir/$ap_type/flash.bin" $ssh_user@$host:/tmp/

echo "scp good!"
echo "${KEA_QUERY4_HWADDR}" > /var/run/kea/done.txt

if [ "${ap_type}" == "e8450-ubi" ];then
  ssh -i $state_dir/id_priv -p $ssh_port -t \
  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
  $ssh_user@$host "ip l show dev wl0-ap | grep ether | awk '{print $2}';ip l show dev wl1-ap | grep ether | awk '{print $2}'" > /var/run/kea/done.txt
else
  ssh -i $state_dir/id_priv -p $ssh_port -t \
  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
  $ssh_user@$host "ip l show dev phy0-ap0 | grep ether | awk '{print $2}';ip l show dev phy0-ap0 | grep ether | awk '{print $2}'" > /var/run/kea/done.txt
fi

echo -e "\n" > /var/run/kea/done.txt

ssh -i $state_dir/id_priv -p $ssh_port -t \
  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
  $ssh_user@$host "grep $flash_sha /etc/scale-release; if \[ \$? == 0 \]; then poweroff; else sysupgrade -n -v /tmp/flash.bin; fi"


echo "Done with $host"
