#!/bin/sh
# The splitaplist script splits the aplist.csv into apmac.csv (map of serial number to mac address)
# and apuse.csv (the rest of the info, not counting the ipv4 network prefix)
#
# there is an additional file roommap.csv that identifies:
#   what building each room prefix is in
#   what the ip range is for that room
#   what map id it would appear on
#
# buildaplist takes these files and creates a new aplist.csv that has the correct combination of information
#
# when editing the aplist directly we tend to change the name and the rest of the stuff stays the same
# this breaks when the spare was in a different building
# it also drags the rest of the per-location information from the spare
#
# This new approach lets us change what AP is where by editing the apuser.csv file
# with the mac changing automatically in the aplist.csv file

while keeping the rest of the per-location information being the samecat apuse.csv  |sed s/,/' '/g |while read name serial ip ch2 ch5 config x y
do
  export mac=`grep "$serial," apmac.csv |cut -f 2 -d , `
  export prefix=`echo "$name" |cut -f 1 -d - `
  grep "^$prefix," roommap.csv |sed s/,/' '/g |while read j ipprefix map
  do
    echo "$name,$serial,$mac,$ipprefix.$ip,$ch2,$ch5,$config,$map,$x,$y"
  done
done
