{
 "title": "Overall AP Status",
 "time": { "from": "2024-03-16T13:33:01.398Z", "to": "2024-03-17T14:43:02.262Z" },
 "panels": [
  {
   "title": "100 Rooms",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(node_time_seconds{ap=~\"1..-[a-z]\"}[5m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "200 Rooms",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "increase(node_time_seconds{ap=~\"2..-[a-z]\"}[5m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ballrooms",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "increase(node_time_seconds{ap=~\"ball.+\"}[5m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expo",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(node_time_seconds{ap=~\"expo.+\"}[5m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Game",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "increase(node_time_seconds{ap=~\"game.+\"}[5m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Low Conf",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "increase(node_time_seconds{ap=~\"lowconf.+\"}[5m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registration Hall",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "increase(node_time_seconds{ap=~\"reghall.+\"}[5m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}