#!/usr/bin/env expect
#
# Script intended to be run for gitlab-runner for CI flashing
#
# This script assumes your root based on the nature of what
# its manipulating: interfaces, gpio pins, etc.

# Set script to debug, equal to expect -d
#exp_internal 1

# Dir where build artifacts should be stored
set workdir "work"

# Make sure dir exists and is owned by correct user
# since gitlab CI will try to clean up old artifacts
# inbetween runs
file mkdir $workdir
file attributes $workdir -owner gitlab-runner
log_file -noappend $workdir/autoflash.log
spawn gpioctl -c 2 OUT
# set Pulldown to keep pin 2 from effecting pin 3
spawn gpioctl -c 3 OUT PD

# Off
spawn gpioctl -p 2 1

# Cleanup interfaces and arp table
spawn ifconfig flash0 down
spawn ifconfig flash0.503 destroy
spawn pkill dnsmasq
spawn arp -d 192.168.1.1
spawn arp -d 192.168.254.100
sleep 2

# on
spawn ifconfig flash0 192.168.1.2 255.255.255.0
spawn gpioctl -p 2 0
spawn gpioctl -p 3 0
set timeout 120
spawn ping -o -i 10 -n 192.168.1.1
expect {
  # renew timer if no reply
  "Unreachable" exp_continue
  "ping*" exp_continue
  "PING*" exp_continue
  "taking countermeasures*"
  "40 bytes from*"
}
# Wait for AP light to be blinking green
sleep 30
spawn gpioctl -p 3 1
# TFTP takes about 10 sec
# bump to timeout to accommodate this
set timeout 30
spawn tftp 192.168.1.1
expect tftp>
send "bin\r"
expect tftp>
send "put factory.img\r"
expect {
  Sent exp_continue
  "tftp>" {
    send "quit\r"
  }
  "receive_packet: timeout" { exit 1 }
  "Try " { exit 1 }
}
# Set back to default
set timeout 10
spawn arp -d 192.168.1.1
spawn ifconfig flash0.503 create
spawn ifconfig flash0.503 inet 192.168.254.1 255.255.255.0
sleep 2

# Our DHCP server to the AP
# This will fail without the full path to dnsmasq, unsure why
spawn /usr/local/sbin/dnsmasq -u gitlab-runner -i flash0.503 --dhcp-range=192.168.254.100,192.168.254.100,255.255.255.0,30s --dhcp-option=3,192.168.254.1

# Ping wait will be set to 10 sec
# Make sure expect timeout is longer than
# ping wait and account for initial ping taking
# longer
set timeout 120
spawn ping -o -i 10 -n 192.168.254.100
expect {
    # renew timer if no reply
    "ping*" exp_continue
    "PING*" exp_continue
    timeout { puts "expect timeout waiting for AP to get DHCP lease"; exit 1 }
}
send_user "\n\nFinished flashing AP!\n\n"
