#!/usr/bin/env expect

set timeout 120

spawn arp -d 192.168.1.1
# Leverage the nix-shell ping for this script
# ubuntu ping as of 18.04,20.04 doesnt seem to
# return the malformed packet
# TODO: Could us single ping and then look at arp table
spawn ping -n 192.168.1.1
expect {
  Unreachable exp_continue
  "taking countermeasures"
}
close
spawn arp -n 192.168.1.1
expect -re "192.168.1.1 *ether *(\[^ \]*) "
spawn tftp 192.168.1.1
expect tftp
send "bin\n"
expect tftp
send "put factory.img\n"
expect tftp
send "quit\n"
close
spawn arp -d 192.168.1.1
send_user "\n\nfinished, do the next AP\n\n"
