#!/bin/bash
#
# This script creates maps that show the network connectivity.
# it is designed to be run from scale-network/swich-configuration/configs
# it runs scripts/gather_lldp_map_data to the file map.parts
# map.parts contains distilled lldp data showing what each device can hear
# This includes a fixup defined in scripts/make_lldp_map.sed that should not be needed if the csv router definitions match their hostnames
# There is also currently a bug in that the pi kiosk images don't set their hostnames via dhcp so they all show up as pi or pi-monitoring. they need to all get a unique name for the diagram
#
# The format is:
# host interface remote
#
# scripts/make_lldp_map.py then takes this data and creates a .diag file
# that can then be used by blockdiag to create the images.
# you tell it which node to start with (the border router) and things external to that are shown as clouds
#

scripts/gather_lldp_map_data

echo "There is also currently a bug in that the pi kiosk images don't set their hostnames via dhcp so they all show up as pi or pi-monitoring. they need to all get a unique name for the diagram. Manually edit map.parts"

scripts/make_lldp_map.py br-mdf-01 map.parts
blockdiag network.diag -T svg -o map.svg
blockdiag network.diag -T png -o map.png
