# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "serverspec"

# needed for ed25519 for net-ssh 5.0 and later
# https://github.com/net-ssh/net-ssh/issues/565
gem 'ed25519', '>= 1.2', '< 2.0'

gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'

gem "rake"
