# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "serverspec"

gem 'ed25519', '>= 1.2', '< 2.0'

gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'

gem "rake"
